demandfp = "BuildingData2018_processed/"
dmodelfp = "BuildingData2018_processed/Models/"
clusterfp = "BuildingData2018_processed/ClusterList.csv"
smodelfp = "SupplyData/"
supplyfp = "Processed2018CompiledWeatherData.csv"
outputfp = "OutputData.csv"
powerreqscsv = 'PowerRequirements.csv'
lookuptable = 'Look Up Table Spreadsheet.csv'
DEMAND_TIME_HORIZONS = 4